export const GET_USERS='GET_USERS'
export const GET_USERS_FAILED='GET_USERS_FAILED'
export const GET_USERS_LOADING='GET_USERS_LOADING'

export const GET_SINGLE_USER='GET_SINGLE_USER'
export const GET_SINGLE_USER_FAILED='GET_SINGLE_USER_FAILED'
export const GET_SINGLE_USER_LOADING='GET_SINGLE_USER_LOADING'

